import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";

const svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 300"><title>Elephant</title><ellipse cx="210" cy="150" rx="120" ry="70" fill="#9ba"/></svg>';
const answer = [{ type: "delta", text: `An elephant.\n\n\`\`\`svg\n${svg}\n\`\`\`` }, { type: "done" }].map(event => JSON.stringify(event)).join("\n") + "\n";

test("folder models, effort, parallel revision, aligned fork, dots, uploads and PDF", async ({ page }, info) => {
  let release: () => void = () => {};
  const ready = new Promise<void>(resolve => { release = resolve; });
  const payloads: { reasoning_effort?: string; messages: { files?: { name: string }[] }[] }[] = [];
  await page.route("**/local-api/llm/v1/models", route => route.fulfill({ json: { object: "list", data: [{ id: "gpt-6.1-sol", object: "model", created: 0, owned_by: "devneya", supportedReasoningEfforts: ["low", "medium", "high", "xhigh"], defaultReasoningEffort: "medium" }] } }));
  await page.route("**/local-api/completion", async route => { payloads.push(route.request().postDataJSON()); if (payloads.length === 1) await ready; await route.fulfill({ contentType: "application/x-ndjson", body: answer }); });
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await expect(page.getByText("New prompt", { exact: true })).toBeVisible();
  const prompt = page.locator(".generation-node").first();
  const input = page.getByLabel("Prompt 1 instruction");
  await expect(input).toHaveAttribute("placeholder", "Ask gpt-6.1-sol");
  await prompt.getByRole("button", { name: "Prompt 1 model picker" }).click();
  await expect(prompt.locator(".model-picker-arrow")).toBeVisible();
  const menu = page.getByRole("dialog", { name: "Prompt 1 models" });
  const folder = menu.locator(".model-group"); await folder.locator("summary").click();
  await expect(folder.getByRole("radio")).toBeHidden(); await folder.locator("summary").click();
  await menu.getByRole("radio", { name: "Prompt 1 gpt-6.1-sol effort low" }).check();
  await menu.getByRole("button", { name: "Done" }).click();
  await input.fill("draw elephant");
  const before = await prompt.boundingBox();
  const compose = await prompt.locator(".prompt-compose").boundingBox();
  const send = await prompt.getByRole("button", { name: "Send prompt" }).boundingBox();
  expect(Math.abs(compose!.y + compose!.height / 2 - send!.y - send!.height / 2)).toBeLessThan(2);
  await input.press("Enter");
  const status = page.getByLabel("Generation in progress"); await expect(status).toBeVisible();
  await expect(status).toHaveCSS("font-size", "14px");
  await expect(status.getByLabel("Characters received")).toHaveCSS("font-size", "22px");
  await expect(status.getByRole("status")).toHaveText("gpt-6.1-sol working");
  await expect(status.getByLabel("Elapsed time")).toHaveCSS("font-size", "13px");
  await expect(page.locator(".generated-node").getByRole("button", { name: "Save as note" })).toHaveCount(0);
  expect((await prompt.boundingBox())!.height).toBe(before!.height);
  await expect(status.getByRole("button", { name: "Fork question" })).toHaveCount(0);
  await prompt.getByRole("button", { name: "Fork", exact: true }).click();
  await expect(status).toBeVisible();
  const fork = page.locator(".generation-node").last();
  await expect(fork.locator("textarea")).toHaveValue("draw elephant");
  expect((await fork.boundingBox())!.height).toBe(before!.height);
  await expect(page.locator(".branch-edge")).toHaveCount(1);
  await expect(page.locator(".branch-edge .react-flow__edge-path")).toHaveAttribute("d", /^M/);
  await page.screenshot({ path: info.outputPath("fork-and-progress.png"), fullPage: true });
  await fork.locator("textarea").fill("draw it differently");
  release();
  await expect(page.locator(".stored-images img")).toHaveCount(1);
  expect(payloads[0]?.reasoning_effort).toBe("low");
  await expect(page.getByLabel("Generation in progress")).toHaveCount(0);
  await input.press("Enter");
  await expect(page.locator(".generated-node")).toHaveCount(1);
  await page.getByRole("button", { name: "fit view", exact: true }).click(); await page.waitForTimeout(300);
  const count = await page.locator(".generation-node").count();
  const dot = page.locator(".generated-node [data-handleid='text-output']");
  await dot.click(); await expect(page.locator(".generation-node")).toHaveCount(count + 1);
  await page.getByRole("button", { name: "fit view", exact: true }).click(); await page.waitForTimeout(300);
  const handle = await dot.boundingBox();
  await page.mouse.move(handle!.x + handle!.width / 2, handle!.y + handle!.height / 2); await page.mouse.down();
  await page.mouse.move(handle!.x + 150, handle!.y - 100, { steps: 15 }); await page.mouse.up();
  await expect(page.locator(".generation-node")).toHaveCount(count + 2);
  await page.getByLabel("Canvas file").setInputFiles({ name: "context.md", mimeType: "text/markdown", buffer: Buffer.from("My elephant is named Miro.") });
  await expect(page.getByLabel("context.md text")).toHaveValue("My elephant is named Miro.");
  const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=", "base64");
  await page.getByLabel("Canvas file").setInputFiles({ name: "elephant.png", mimeType: "image/png", buffer: png });
  await expect(page.locator(".stored-files img")).toBeVisible();
  const fileDot = page.locator(".file-node").filter({ has: page.locator(".stored-files") }).locator("[data-handleid='text-output']");
  await fileDot.click();
  const filePrompt = page.locator(".generation-node").last();
  await filePrompt.locator("textarea").fill("What is this image?"); await filePrompt.getByRole("button", { name: "Send prompt" }).click();
  await expect(page.locator(".stored-images img")).toHaveCount(2);
  expect(payloads.at(-1)?.messages.some(message => message.files?.[0]?.name === "elephant.png")).toBe(true);
  await page.getByRole("button", { name: "fit view", exact: true }).click(); await page.waitForTimeout(300);
  await page.screenshot({ path: info.outputPath("canvas-controls.png"), fullPage: true });
  const downloadPromise = page.waitForEvent("download"); await page.getByRole("button", { name: "Export options", exact: true }).click(); await page.getByLabel("Export workspace", { exact: true }).click();
  const exported = JSON.parse(await readFile((await (await downloadPromise).path())!, "utf8"));
  expect(exported.workspace.flows[0].nodes.some((node: { data: { files?: unknown[] } }) => node.data.files?.length)).toBe(true);
  await page.getByLabel("Export options", { exact: true }).click();
  const popupPromise = page.waitForEvent("popup"); await page.getByRole("button", { name: /Print \/ Save PDF/ }).click();
  const popup = await popupPromise; await expect(popup.getByRole("heading", { name: "Default flow" })).toBeVisible();
  await expect(popup.locator("img")).toHaveCount(3);
  await popup.screenshot({ path: info.outputPath("print-preview.png"), fullPage: true });
  const pdf = await popup.pdf({ path: info.outputPath("flow.pdf"), printBackground: true }); expect(pdf.length).toBeGreaterThan(1000);
  await popup.close();
  await expect(page.getByText("Saved locally", { exact: true })).toBeVisible(); await page.reload();
  await expect(page.locator(".stored-files img")).toHaveCount(1);
  await expect(page.getByLabel("context.md text")).toHaveValue("My elephant is named Miro.");
  expect(errors).toEqual([]);
});

test("menus fit at the viewport edge, context exclusions reach the model, and delete sits on the wire", async ({ page }, info) => {
  await page.setViewportSize({ width: 1000, height: 760 });
  const requests: { messages: { content: string }[] }[] = [];
  await page.route("**/local-api/llm/v1/models", route => route.fulfill({ json: { object: "list", data: [{ id: "gpt-6.1-sol", object: "model", created: 0, owned_by: "devneya", supportedReasoningEfforts: ["low", "xhigh"], defaultReasoningEffort: "low" }] } }));
  await page.route("**/local-api/completion", route => {
    requests.push(route.request().postDataJSON());
    return route.fulfill({ contentType: "application/x-ndjson", body: [{ type: "delta", text: "KEEP this answer." }, { type: "done" }].map(event => JSON.stringify(event)).join("\n") + "\n" });
  });
  await page.goto("/");
  const first = page.locator(".generation-node").first();
  await expect(first.getByRole("button", { name: /model picker/ })).toContainText("gpt-6.1-sol");
  const card = await first.boundingBox(); const header = await first.locator(".node-header").boundingBox();
  const dx = 1000 - card!.width - 16 - card!.x, dy = 760 - card!.height - 16 - card!.y;
  await page.mouse.move(header!.x + 15, header!.y + 10); await page.mouse.down();
  await page.mouse.move(header!.x + 15 + dx, header!.y + 10 + dy, { steps: 15 }); await page.mouse.up();
  await first.getByRole("button", { name: /model picker/ }).click();
  const menu = page.getByRole("dialog", { name: "Prompt 1 models" });
  await expect(menu).toBeVisible();
  const menuBox = await menu.boundingBox();
  expect(menuBox!.x).toBeGreaterThanOrEqual(12); expect(menuBox!.x + menuBox!.width).toBeLessThanOrEqual(988);
  expect(menuBox!.y).toBeGreaterThanOrEqual(12); expect(menuBox!.y + menuBox!.height).toBeLessThanOrEqual(748);
  await expect(menu.getByRole("radiogroup", { name: "Prompt 1 gpt-6.1-sol effort levels" })).toBeVisible();
  await expect(menu.getByRole("radio", { name: "Prompt 1 gpt-6.1-sol effort xhigh" })).toBeVisible();
  await page.screenshot({ path: info.outputPath("model-menu-at-edge.png"), fullPage: true });
  await menu.getByRole("button", { name: "Done" }).click();
  await first.locator("textarea").fill("EXCLUDE this request from future context."); await first.locator("textarea").press("Enter");
  const next = page.getByLabel("Prompt 2 instruction"); await expect(next).toBeVisible();
  const prompt = page.locator(".generation-node").filter({ has: next });
  await prompt.locator(".context-disclosure summary").click();
  await expect(prompt.locator(".context-panel")).toContainText("EXCLUDE");
  await prompt.getByRole("button", { name: "Remove context item 1" }).click();
  await expect(prompt.locator(".context-panel")).not.toContainText("EXCLUDE");
  await expect(prompt.locator(".context-panel")).toContainText("KEEP");
  await page.screenshot({ path: info.outputPath("trimmed-context.png"), fullPage: true });
  await next.fill("Next question."); await next.press("Enter");
  await expect(page.locator(".generated-node")).toHaveCount(2);
  expect(requests[1]?.messages).toEqual([{ role: "assistant", content: "KEEP this answer." }, { role: "user", content: "Next question." }]);
  const third = page.locator(".generation-node").filter({ has: page.getByLabel("Prompt 3 instruction") });
  await expect(third.locator("textarea")).toBeVisible();
  await third.locator(".context-disclosure summary").click();
  await third.getByRole("button", { name: "Clear context" }).click();
  await third.locator("textarea").fill("Fresh request."); await third.locator("textarea").press("Enter");
  await expect(page.locator(".generated-node")).toHaveCount(3);
  expect(requests[2]?.messages).toEqual([{ role: "user", content: "Fresh request." }]);
  await page.getByRole("button", { name: "fit view", exact: true }).click(); await page.waitForTimeout(300);
  await page.locator(".managed-edge-hoverzone").first().hover();
  const remove = page.getByRole("button", { name: "Remove connection" }); await expect(remove).toBeVisible();
  const distance = await remove.evaluate(button => {
    const rectangle = button.getBoundingClientRect(); const center = { x: rectangle.x + rectangle.width / 2, y: rectangle.y + rectangle.height / 2 };
    const paths = [...document.querySelectorAll<SVGPathElement>(".input-edge .react-flow__edge-path")];
    return Math.min(...paths.flatMap(path => { const matrix = path.getScreenCTM(); if (!matrix) return [Infinity]; const length = path.getTotalLength(); return Array.from({ length: 201 }, (_, i) => { const point = path.getPointAtLength(length * i / 200).matrixTransform(matrix); return Math.hypot(center.x - point.x, center.y - point.y); }); }));
  });
  expect(distance).toBeLessThan(3);
  await page.screenshot({ path: info.outputPath("edge-control.png"), fullPage: true });
});

const uploadCheckPdf = () => {
  const content = "BT /F1 18 Tf 40 100 Td (The upload check word is COBALT.) Tj ET";
  const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 450 180] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", `<< /Length ${content.length} >>\nstream\n${content}\nendstream`];
  let source = "%PDF-1.4\n"; const offsets = [0];
  for (let index = 0; index < objects.length; index++) { offsets.push(Buffer.byteLength(source)); source += `${index + 1} 0 obj\n${objects[index]}\nendobj\n`; }
  const xref = Buffer.byteLength(source);
  source += `xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(offset => `${String(offset).padStart(10, "0")} 00000 n \n`).join("")}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(source);
};

test("live Codex reads an uploaded PDF at the selected effort", async ({ page }, info) => {
  test.skip(process.env.CANVAS_FILES_LIVE !== "1", "Explicit live file inference test.");
  await page.goto("/");
  await expect(page.getByRole("button", { name: "Prompt 1 model picker" })).toContainText("gpt-6.1-sol", { timeout: 60_000 });
  await page.getByLabel("Canvas file").setInputFiles({ name: "upload-check.pdf", mimeType: "application/pdf", buffer: uploadCheckPdf() });
  const upload = page.locator(".file-node").filter({ has: page.locator(".stored-files") });
  await expect(upload.getByText("PDF", { exact: true })).toBeVisible();
  await upload.locator("[data-handleid='text-output']").click();
  const prompt = page.locator(".generation-node").last();
  await prompt.getByRole("button", { name: /model picker/ }).click();
  await page.getByRole("radio", { name: /model gpt-6-luna$/ }).check();
  await page.getByRole("radio", { name: /gpt-6-luna effort low$/ }).check();
  await page.keyboard.press("Escape");
  await prompt.locator("textarea").fill("Read the attached PDF and reply with only its upload check word.");
  const responsePromise = page.waitForResponse(response => response.url().endsWith("/local-api/completion"), { timeout: 610_000 });
  await prompt.getByRole("button", { name: "Send prompt" }).click();
  const response = await responsePromise; const output = await response.text();
  expect(response.request().postDataJSON().reasoning_effort).toBe("low");
  expect(response.ok()).toBe(true); expect(output).not.toContain('"type":"error"');
  await expect(page.locator(".generated-content")).toContainText("COBALT");
  await page.getByRole("button", { name: "fit view", exact: true }).click(); await page.waitForTimeout(300);
  await page.screenshot({ path: info.outputPath("live-file-answer.png"), fullPage: true });
});
