import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";

const svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 320"><title>Elephant</title><rect width="500" height="320" fill="#f4f5ee"/><ellipse cx="230" cy="160" rx="135" ry="85" fill="#84969d"/><circle cx="350" cy="150" r="55" fill="#84969d"/><ellipse cx="330" cy="140" rx="40" ry="52" fill="#9dabb0"/><path d="M 395 160 Q 440 240 410 245" stroke="#84969d" stroke-width="25" fill="none"/><circle cx="378" cy="132" r="5" fill="#34463e"/><path d="M 155 210 L 150 275 M 295 215 L 300 275" stroke="#84969d" stroke-width="35"/></svg>';

test("uploads have file previews, left dots create prompts, and effort uses compact choices", async ({ page }, info) => {
  let release: () => void = () => {};
  const ready = new Promise<void>(resolve => { release = resolve; });
  const requests: { reasoning_effort: string; messages: { content: string }[] }[] = [];
  await page.route("**/local-api/llm/v1/models", route => route.fulfill({ json: { object: "list", data: [{ id: "gpt-6.1-sol", object: "model", created: 0, owned_by: "devneya", supportedReasoningEfforts: ["low", "medium", "high", "xhigh", "max", "ultra"], defaultReasoningEffort: "xhigh" }] } }));
  await page.route("**/local-api/completion", async route => { requests.push(route.request().postDataJSON()); await ready; await route.fulfill({ contentType: "application/x-ndjson", body: '{"type":"delta","text":"An elephant."}\n{"type":"done"}\n' }); });
  await page.goto("/");
  await page.getByLabel("Canvas file").setInputFiles({ name: "Elephant.svg", mimeType: "image/svg+xml", buffer: Buffer.from(svg) });
  const file = page.locator(".file-node").filter({ hasText: "Elephant.svg" });
  await expect(file.locator(".stored-images img")).toBeVisible();
  await expect(file.locator(".manual-textarea")).toHaveCount(0);
  await expect(file).toHaveCSS("background-color", "rgb(245, 246, 243)");
  await expect(file.getByText("SVG", { exact: true })).toBeVisible();
  const initial = await page.locator(".generation-node").count();
  await file.getByRole("button", { name: "New prompt from left dot", exact: true }).click();
  await expect(page.locator(".generation-node")).toHaveCount(initial + 1);
  const prompt = page.locator(".generation-node").last();
  await expect(prompt.getByRole("button", { name: /model picker/ })).toContainText("gpt-6.1-sol");
  const source = await file.boundingBox(); const target = await prompt.boundingBox();
  expect(target!.x + target!.width).toBeLessThan(source!.x);
  const picker = prompt.getByRole("button", { name: /model picker/ }); const pickerBox = await picker.boundingBox();
  expect(pickerBox!.x - target!.x).toBeLessThan(40);
  await picker.click();
  const menu = page.getByRole("dialog", { name: "Prompt 2 models" });
  await expect(menu.locator("select")).toHaveCount(0);
  const choices = menu.getByRole("radiogroup", { name: /effort levels/ });
  await expect(choices.getByRole("radio")).toHaveCount(6);
  await choices.getByRole("radio", { name: /effort low$/ }).check();
  await expect(picker).toContainText("low");
  await page.screenshot({ path: info.outputPath("file-and-effort.png"), fullPage: true });
  await menu.getByRole("button", { name: "Done" }).click();
  await prompt.locator("textarea").fill("What is in this file?"); await prompt.locator("textarea").press("Enter");
  const status = page.getByLabel("Generation in progress"); await expect(status).toBeVisible();
  await expect(status.getByLabel("Elapsed time")).toHaveCSS("font-size", "13px");
  await expect(status).toHaveCSS("background-color", "rgba(0, 0, 0, 0)");
  await page.screenshot({ path: info.outputPath("file-and-progress.png"), fullPage: true });
  expect(requests[0]?.reasoning_effort).toBe("low");
  expect(requests[0]?.messages.some(message => message.content.includes(svg))).toBe(true);
  release(); await expect(page.locator(".generated-content")).toContainText("An elephant.");
  await page.getByRole("button", { name: "fit view", exact: true }).click(); await page.waitForTimeout(300);
  const beforeDrag = await page.locator(".generation-node").count();
  const dot = await file.locator("[data-handleid='text-left-output']").boundingBox();
  await page.mouse.move(dot!.x + dot!.width / 2, dot!.y + dot!.height / 2); await page.mouse.down();
  await page.mouse.move(dot!.x - 110, dot!.y + 220, { steps: 15 }); await page.mouse.up();
  await expect(page.locator(".generation-node")).toHaveCount(beforeDrag + 1);
  const saving = page.waitForEvent("download"); await page.getByRole("button", { name: "Export options", exact: true }).click(); await page.getByLabel("Export workspace", { exact: true }).click();
  const saved = JSON.parse(await readFile((await (await saving).path())!, "utf8"));
  const flow = saved.workspace.flows[0];
  const fileNode = flow.nodes.find((node: { data: { upload?: unknown } }) => node.data.upload);
  expect(flow.edges.filter((edge: { source: string; sourceHandle: string }) => edge.source === fileNode.id && edge.sourceHandle === "text-left-output")).toHaveLength(2);
  flow.nodes.push({ ...fileNode, id: "legacy-svg", position: { x: 0, y: 700 }, data: { kind: "text", origin: "manual", title: "Legacy.svg", text: svg } });
  await page.getByLabel("Workspace JSON file").setInputFiles({ name: "legacy.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(saved)) });
  await expect(page.locator(".file-node")).toHaveCount(2);
  await expect(page.locator(".file-node").filter({ hasText: "Legacy.svg" }).locator("img")).toHaveCount(1);
  await expect(page.getByText("Saved locally", { exact: true })).toBeVisible(); await page.reload();
  await expect(page.locator(".file-node")).toHaveCount(2);
});
