import { expect, test } from "@playwright/test";

test("restored boxes support a live Codex answer, notes and forks", async ({ page }, info) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  const input = page.getByLabel("Prompt 1 instruction");
  await expect(input).toBeVisible();
  await expect(page.getByRole("button", { name: "Prompt 1 model picker" })).toContainText("gpt-6.1-sol", { timeout: 60_000 });
  await expect(page.locator(".experience-studio, .move-board, .work-surface")).toHaveCount(0);
  await input.fill("In two short sentences, explain why the sky looks blue. Use plain text.");
  const responsePromise = page.waitForResponse(response => response.url().endsWith("/local-api/completion"), { timeout: 610_000 });
  await input.press("Enter");
  const response = await responsePromise;
  expect(response.ok()).toBe(true);
  expect(response.request().postDataJSON().instructions).toContain("Answer directly using Markdown");
  await expect(page.getByLabel("Generation in progress")).toHaveCount(0);
  const answer = page.locator(".generated-node");
  await expect(answer).toHaveCount(1);
  await expect(answer.locator(".generated-content")).not.toBeEmpty();
  await expect(answer.locator(".generated-content")).toHaveCSS("font-family", 'Georgia, "Times New Roman", serif');
  await expect(answer).toHaveCSS("width", "480px");
  await expect(page.locator(".generation-node")).toHaveCount(2);
  await answer.getByRole("button", { name: "Save as note" }).click();
  await expect(page.locator(".manual-node")).toHaveCount(1);
  await answer.getByRole("button", { name: "Fork", exact: true }).click();
  await expect(page.locator(".generation-node")).toHaveCount(3);
  await page.getByRole("button", { name: "fit view", exact: true }).click();
  await page.waitForTimeout(500);
  await page.screenshot({ path: info.outputPath("restored-desktop.png"), fullPage: true });
  await expect(page.getByText("Saved locally", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator(".generated-node")).toHaveCount(1);
  await expect(page.locator(".manual-node")).toHaveCount(1);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "fit view", exact: true }).click();
  await page.waitForTimeout(500);
  await page.screenshot({ path: info.outputPath("restored-mobile.png"), fullPage: true });
  expect(await page.evaluate(() => document.body.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
