import { expect, test } from "@playwright/test";
import { readFile, writeFile } from "node:fs/promises";

// Synthetic philosophical test data, not personal information from the user.
const note = "A temporary community garden can matter while it exists.";
test("human and model revise the same workspace with undo and persistence", async ({ page }, info) => {
  page.setDefaultTimeout(20000);
  const first = JSON.parse(await readFile(process.env.SURFACE_FIRST_RESPONSE ?? new URL("../fixtures/surface-first.json", import.meta.url), "utf8"));
  let count = 0;
  await page.route("**/local-api/completion", async (route) => {
    count += 1;
    if (count === 1) return route.fulfill({ json: first });
    const request = route.request().postDataJSON();
    const context = JSON.parse(request.messages[0].content);
    expect(context.workspace.objects.find((o: {id: string}) => o.id === "live_meaning").text).toBe(note);
    await writeFile(info.outputPath("second-request.json"), JSON.stringify(request));
    if (!process.env.SURFACE_LIVE_FOLLOWUP) return route.fulfill({ json: JSON.parse(await readFile(process.env.SURFACE_SECOND_RESPONSE ?? new URL("../fixtures/surface-revision.json", import.meta.url), "utf8")) });
    return route.continue();
  });
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/?view=surface");
  await expect(page.getByLabel("Workspace model picker")).toContainText("gpt-6.1-sol", { timeout: 60000 });
  await page.screenshot({ path: info.outputPath("empty-workspace.png"), fullPage: true });
  await page.getByLabel("Work together", { exact: true }).fill("meaning of life?");
  await page.getByRole("button", { name: "Make a move" }).click();
  await expect(page.locator(".work-object")).toHaveCount(6);
  await expect(page.getByRole("complementary", { name: "Your requests" })).toContainText("meaning of life?");
  await page.screenshot({ path: info.outputPath("first-workspace.png"), fullPage: true });
  const live = page.getByRole("region", { name: "Live meaning", exact: true });
  await live.dblclick();
  await page.getByRole("dialog", { name: "Edit workspace object" }).getByRole("textbox", { name: "Text", exact: true }).fill(note);
  await page.getByRole("button", { name: "Keep changes" }).click();
  await expect(live).toContainText(note);
  const before = await live.boundingBox();
  await page.mouse.move(before!.x + 50, before!.y + 20);
  await page.mouse.down();
  await page.mouse.move(before!.x + 30, before!.y + 45, { steps: 10 });
  await page.mouse.up();
  const after = await live.boundingBox();
  expect(Math.abs(after!.x - before!.x)).toBeGreaterThan(10);
  const exportState = async (name: string) => {
    await expect(page.getByText("Saved locally", { exact: true })).toBeVisible();
    const download = page.waitForEvent("download");
    await page.getByRole("button", { name: "Export workspace" }).click();
    const file = await download; const path = info.outputPath(name);
    await file.saveAs(path);
    const exported = JSON.parse(await readFile(path, "utf8"));
    return exported.workspace.flows.find((f: {id: string}) => f.id === exported.workspace.activeFlowId).surface;
  };
  const beforeModel = await exportState("human-edited.devneya.json");
  await page.getByRole("button", { name: "Change the work", exact: true }).click();
  await page.getByLabel("Work together", { exact: true }).fill("Use the fictional community-garden example in my edited note to challenge the idea that meaning needs a permanent legacy. Keep that note's exact wording and position. Add a claim and a counterexample, connect them meaningfully to the note, and make room by revising other existing objects if necessary.");
  const responsePromise = page.waitForResponse((response) => response.url().endsWith("/local-api/completion"), { timeout: 610000 });
  await page.getByRole("button", { name: "Make a move" }).click();
  const response = await responsePromise;
  const payload = await response.json();
  await writeFile(info.outputPath("second-response.json"), JSON.stringify(payload));
  expect(response.ok()).toBe(true);
  await expect(page.getByRole("status").filter({ hasText: "Working…" })).toHaveCount(0, { timeout: 15000 });
  await expect(page.locator(".work-error")).toHaveCount(0);
  await expect(live).toContainText(note);
  const revised = await exportState("revised-workspace.devneya.json");
  expect(revised.turns).toHaveLength(2);
  expect(revised.objects.find((o: {id: string}) => o.id === "live_meaning")).toMatchObject(beforeModel.objects.find((o: {id: string}) => o.id === "live_meaning"));
  expect(revised.links.length).toBeGreaterThan(0);
  await page.screenshot({ path: info.outputPath("revised-workspace.png"), fullPage: true });
  await page.getByRole("button", { name: "Undo last change" }).click();
  const undone = await exportState("undone.devneya.json");
  expect(undone.objects).toEqual(beforeModel.objects);
  expect(undone.links).toEqual(beforeModel.links);
  await page.getByRole("button", { name: "Redo last change" }).click();
  const redone = await exportState("redone.devneya.json");
  expect(redone.objects).toEqual(revised.objects);
  expect(redone.links).toEqual(revised.links);
  await page.reload();
  await expect(page.getByRole("region", { name: "Live meaning", exact: true })).toContainText(note);
  await expect(page.locator(".work-object")).toHaveCount(revised.objects.length);
  await page.getByRole("region", { name: "Live meaning", exact: true }).click();
  await page.getByRole("region", { name: "Discover meaning", exact: true }).click({ modifiers: ["Shift"] });
  await expect(page.getByRole("toolbar", { name: "Selected objects" })).toContainText("2 selected");
  await page.getByRole("button", { name: "Connect", exact: true }).click();
  const connected = await exportState("human-connected.devneya.json");
  expect(connected.links).toHaveLength(revised.links.length + 1);
  await page.getByRole("button", { name: "Earlier threads", exact: true }).click();
  await expect(page.getByRole("button", { name: "Send prompt", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Work together ↗", exact: true }).click();
  await expect(page.locator(".work-object")).toHaveCount(revised.objects.length);
  expect(count).toBe(2);
  expect(errors).toEqual([]);
});
